[package]
name = "mustang-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3.8"
thiserror = "2.0.17"
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }

[dev-dependencies]
glob = "0.3.3"
diff = "0.1.13"
rayon = "1.11.0"

[features]
jlink = []
